### Listar todas as tarefas
GET http://localhost:5000/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5000/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Me aproximar do meu papagaio",
    "descricao": "Me aproximar do meu papagaio",
    "categoriaId": "b9cf9b2b-bd80-4dfc-ac74-fd8a222c68ed"
}


###Alterar uma nova tarefa
PUT http://localhost:5000/tarefas/alterar/f4262fc4-204b-4166-aba5-b79deb41a899


###Listar tarefas não concluidas
GET http://localhost:5000/tarefas/naoconcluidas


###Listar tarefas concluídas
GET http://localhost:5000/tarefas/concluidas